### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

### ISSUE THREAD

**Issue by praveenjm** [hivivo/ngx-json-viewer#148]
Getting this error while building the project, not sure what to do to resolve it. It was working fine with node 14.18.3, just to test some latest project, uninstalled this node version for some time and after reinstalling same 14.18.3 this error is occuring. Appreciate the help here.
✖ Compiling with Angular sources in Ivy full compilation mode.
node_modules/ngx-json-viewer/src/ngx-json-viewer/ngx-json-viewer.component.d.ts:23:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s). 
static ɵcmp: i0.ɵɵComponentDeclaration<NgxJsonViewerComponent, "ngx-json-viewer", never, { "json": "json"; "expanded": "expanded"; "depth": "depth"; "_currentDepth": "_currentDepth"; }, {}, never, never, false>;

**Comment by huhouhua** [comment]
I also encountered this problem
![image](https://github.com/hivivo/ngx-json-viewer/assets/40319281/8e1679ea-5090-4de0-96e7-5c8dc6bd7345)

**Comment by enisz** [comment]
I'm facing the same issue with `"@angular/core": "12.2.16"`, `"ngx-json-viewer": "3.2.1",` and node version `v16.20.2`.

```
Error: node_modules/ngx-json-viewer/src/ngx-json-viewer/ngx-json-viewer.component.d.ts:23:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

23     static ɵcmp: i0.ɵɵComponentDeclaration<NgxJsonViewerComponent, "ngx-json-viewer", never, { "json": "json"; "expanded": "expanded"; "depth": "depth"; "_currentDepth": "_currentDepth"; }, {}, never, never, false>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✖ Failed to compile.
```

Should I use another version of this package for this angular version?

[edit]

Never mind, it seems I've ignored this part of the readme:

```For older Angular:

# For Angular 4/5/6/7+:
npm install ngx-json-viewer@2

# For Angular 2:
npm install ngx-json-viewer@1
```

For my version of angular (12) version 2.4.0 is the latest supported version which works like a charm.
